# xrandr \
#   --output eDP-1 --auto --pos 0x0 --rotate normal \
#   --output DP-1 --primary --auto --pos 0x-2161 --rotate normal --scale 1.5x1.5
# xrandr \
#   --output eDP-1 --auto --pos 0x0 --rotate normal \
#   --output DP-1 --primary --auto --pos 0x-2160 --rotate normal --scale 1.5x1.5
# xrandr \
#   --output eDP-1 --auto --pos 0x0 --rotate normal \
#   --output eDP-1-1 --auto --pos 0x0 --rotate normal \
#   --output DP-1 --primary --auto --pos 0x-2160 --rotate normal --scale 1.5x1.5 \
#   --output DP-1-1 --primary --auto --pos 0x-2160 --rotate normal --scale 1.5x1.5
